---
- name: copy artifact
  become: true
  copy: 
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Extract artifact files
  become: true
  shell: |
    cd /home/ubuntu
    tar -xvf artifact.tar.gz
- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start

